# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c9d1a5245e10ccdb448c1f8172c367acf62fd3fde531f5c6605a1a6e288adf8711a574c3f9546a9ab8ff47540ad7798ffd7165205161cea580875bcf8fa3d7d

test:
  secret_key_base: 91251c5356e613d7ebba9ee5f322ff09e2018d0b5d29213ae3d817a0bedecc1b484fa6337c2609abeeb625ba00bccb93bfd1af4a1580e28d91a468a04380a894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
